### ISSUE TITLE
Resturctre

### ISSUE THREAD

**Issue by Strooss** [osamayy/azkar-db#3]
اشوف لو تكون بدل اراي تكون اراي فيها اوبجكت كل ذكر عشان النظام

**Comment by osamayy** [comment]
شكرا على ملاحظتك،

بعد التدقيق لاحظت برنامج SQLiteStudio يقوم بتصديرها ك array
أما DB browser فيقوم بتصديرها ك array of objects

 تم إضافة ملف azkar_obj.json ك array of objects
